---
- name: install common dependencies
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - git
    - build-essential
    - libtool
    - libssl-dev
    - autoconf
    - automake
    - unzip
  when: ansible_os_family == "Debian"

- name: install add-apt-repostory
  sudo: yes
  apt: name=software-properties-common state=latest
